// Explicit anchors reviewed against the same local revision as source-map.mjs.
// These are resolved at build time; no guessed line numbers or Python imports.
const refs = {
  cli: ['vllm/entrypoints/cli/serve.py', 'ServeSubcommand.cmd'],
  python: ['vllm/entrypoints/launchers/api_server/entry.py', 'main'],
  headless: ['vllm/entrypoints/cli/serve.py', 'run_headless'],
  args: ['vllm/engine/arg_utils.py', 'EngineArgs.add_cli_args'],
  config: ['vllm/engine/arg_utils.py', 'EngineArgs.create_engine_config'],
  defaults: [
    'vllm/engine/arg_utils.py',
    'EngineArgs._set_default_chunked_prefill_and_prefix_caching_args',
  ],
  validation: ['vllm/config/vllm.py', 'VllmConfig.__post_init__'],
  parallel: ['vllm/config/parallel.py', 'ParallelConfig.__post_init__'],
  runnerChoice: ['vllm/config/vllm.py', 'VllmConfig.use_v2_model_runner'],
  schedulerChoice: ['vllm/config/scheduler.py', 'SchedulerConfig.get_scheduler_cls'],
  executor: ['vllm/v1/executor/abstract.py', 'Executor.get_class'],
  engine: ['vllm/v1/engine/async_llm.py', 'AsyncLLM.from_vllm_config'],
  loader: ['vllm/model_executor/model_loader/__init__.py', 'get_model'],
  quantization: ['vllm/model_executor/layers/quantization/__init__.py', 'get_quantization_config'],
  attention: ['vllm/v1/attention/selector.py', 'get_attn_backend'],
  kvInit: ['vllm/v1/engine/core.py', 'EngineCore._initialize_kv_caches'],
  warmup: ['vllm/v1/executor/abstract.py', 'Executor.compile_or_warm_up_model'],
  routers: ['vllm/entrypoints/launchers/api_server/routers.py', 'register_api_routers'],
  chat: [
    'vllm/entrypoints/openai/chat_completion/serving.py',
    'OpenAIServingChat.create_chat_completion',
  ],
  completion: [
    'vllm/entrypoints/openai/completion/serving.py',
    'OpenAIServingCompletion.create_completion',
  ],
  embedding: ['vllm/entrypoints/pooling/base/serving.py', 'PoolingBaseServing.__call__'],
  input: ['vllm/v1/engine/input_processor.py', 'InputProcessor.process_inputs'],
  async: ['vllm/v1/engine/async_llm.py', 'AsyncLLM.add_request'],
  dp: ['vllm/v1/engine/core_client.py', 'DPLBAsyncMPClient.get_core_engine_for_request'],
  queue: ['vllm/v1/engine/core.py', 'EngineCore.add_request'],
  schedule: ['vllm/v1/core/sched/scheduler.py', 'Scheduler.schedule'],
  asyncSchedule: ['vllm/v1/core/sched/async_scheduler.py', 'AsyncScheduler._update_after_schedule'],
  prefix: ['vllm/v1/core/kv_cache_manager.py', 'KVCacheManager.get_computed_blocks'],
  allocate: ['vllm/v1/core/kv_cache_manager.py', 'KVCacheManager.allocate_slots'],
  transfer: [
    'vllm/distributed/kv_transfer/kv_connector/factory.py',
    'KVConnectorFactory.create_connector',
  ],
  kvLoad: [
    'vllm/distributed/kv_transfer/kv_connector/v1/base.py',
    'KVConnectorBase_V1.start_load_kv',
  ],
  step: ['vllm/v1/engine/core.py', 'EngineCore.step'],
  batchStep: ['vllm/v1/engine/core.py', 'EngineCore.step_with_batch_queue'],
  worker: ['vllm/v1/worker/gpu_worker.py', 'Worker.execute_model'],
  runnerV1: ['vllm/v1/worker/gpu_model_runner.py', 'GPUModelRunner.execute_model'],
  runnerV2: ['vllm/v1/worker/gpu/model_runner.py', 'GPUModelRunner.execute_model'],
  sampleV1: ['vllm/v1/worker/gpu_model_runner.py', 'GPUModelRunner.sample_tokens'],
  sampleV2: ['vllm/v1/worker/gpu/model_runner.py', 'GPUModelRunner.sample_tokens'],
  poolV1: ['vllm/v1/worker/gpu_model_runner.py', 'GPUModelRunner._pool'],
  poolV2: ['vllm/v1/worker/gpu/model_runner.py', 'GPUModelRunner.pool'],
  tp: ['vllm/model_executor/layers/linear.py', 'RowParallelLinear.forward'],
  pp: ['vllm/distributed/parallel_state.py', 'GroupCoordinator.send_tensor_dict'],
  ep: ['vllm/model_executor/layers/fused_moe/layer.py', 'FusedMoEFactory'],
  eplb: ['vllm/distributed/eplb/eplb_state.py', 'EplbState.step'],
  lora: ['vllm/lora/worker_manager.py', 'WorkerLoRAManager.set_active_adapters'],
  mm: ['vllm/v1/worker/gpu_model_runner.py', 'GPUModelRunner._execute_mm_encoder'],
  structured: ['vllm/v1/structured_output/__init__.py', 'StructuredOutputManager.grammar_bitmask'],
  speculative: ['vllm/config/speculative.py', 'SpeculativeConfig.__post_init__'],
  graph: ['vllm/compilation/cuda_graph.py', 'CUDAGraphWrapper.__call__'],
  update: ['vllm/v1/core/sched/scheduler.py', 'Scheduler.update_from_output'],
  output: ['vllm/v1/engine/output_processor.py', 'OutputProcessor.process_outputs'],
  stream: [
    'vllm/entrypoints/openai/chat_completion/serving.py',
    'OpenAIServingChat.chat_completion_stream_generator',
  ],
  full: [
    'vllm/entrypoints/openai/chat_completion/serving.py',
    'OpenAIServingChat.chat_completion_full_generator',
  ],
  completionStream: [
    'vllm/entrypoints/openai/completion/serving.py',
    'OpenAIServingCompletion.completion_stream_generator',
  ],
  completionFull: [
    'vllm/entrypoints/openai/completion/serving.py',
    'OpenAIServingCompletion.request_output_to_completion_response',
  ],
  embeddingOutput: [
    'vllm/entrypoints/pooling/embed/serving.py',
    'ServingEmbedding._build_response',
  ],
};

export const commandSources = Object.fromEntries(
  Object.entries(refs).map(([id, [path, symbol]]) => [id, { path, symbol }]),
);
